services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
      - ./backend/static/uploads:/app/static/uploads
    expose:
      - "8000"
    networks:
      - portfolio-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=https://dbtech.cloud/api
    networks:
      - portfolio-network

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/static/uploads:/app/static/uploads:ro
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-var:/var/lib/letsencrypt:ro
      - webroot:/var/www/certbot:ro
    depends_on:
      - backend
      - frontend
    volumes_from:
      - frontend:ro
    networks:
      - portfolio-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  webroot:
